# NMake makefile

BINARIES = bin
LIBRARIES = lib
BUILD = build

all: $(BUILD)
	@CD $(BUILD) && cmake -G "NMake Makefiles" .. && $(MAKE)

clean:
	@RD /S /Q $(BINARIES) $(LIBRARIES) $(BUILD) 2>NUL || REM

test:
	@CD $(BUILD) && ctest

$(BUILD):
	@MKDIR $@
